### ISSUE TITLE
Add Office Hours

### ISSUE THREAD

**Issue by kbuffardi** [ChicoState/SDM-Spring2023#10]
In a dedicated `office_hours.md` file:

- [ ] add the information from the "Office Hours" section of the course syllabus
- [ ] maintain the same formatting as the original
- [ ] add a link to `office_hours.md` called "Office Hours" in the `README.md` file

**Comment by Jooms** [comment]
Dibs?

**Comment by kbuffardi** [comment]
@Jooms it's yours

**Comment by Jooms** [comment]
Ready for review.
