### ISSUE TITLE
Add Learning Outcomes section

### ISSUE THREAD

**Issue by kbuffardi** [ChicoState/SDM-Spring2023#4]
In a dedicated `outcomes.md` file:

- [ ] add the information from the "Learning Outcomes" section of the course syllabus
- [ ] maintain the same formatting as the original
- [ ] add a link to `outcomes.md` called "Learning Outcomes" in the `README.md` file

**Comment by Gajjela-Koushik-Reddy** [comment]
added learning outcomes and partially populated it.

**Comment by hardikpatil** [comment]
Done

**Comment by arshiya19** [comment]
linked outcomes.md file in README.md and added the remaining information to learning outcomes module
